spring.application.name=govai

# PostgreSQL (pgvector container name = postgres)
spring.datasource.url=jdbc:postgresql://postgres:5432/govai
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Spring AI Ollama (container name = ollama)
spring.ai.ollama.base-url=http://ollama:11434
spring.ai.ollama.chat.model=llama3
spring.ai.ollama.embedding.model=nomic-embed-text

# pgvector
spring.ai.vectorstore.pgvector.initialize-schema=true

# optional (recommended)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

server.port=8080